### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by peter2022Begin** [ayu250/iOS-GridView#1]
![snip20180619_22](https://user-images.githubusercontent.com/38389546/41589098-33bf73f0-73e6-11e8-97e3-0be93f7bed06.png)
这里报错了

**Comment by ayu250** [comment]
收到，后面改东西了，漏提交了，晚一点会提交的，谢谢




发自网易邮箱大师
在2018年06月19日 17:28，peterios2016 写道：


这里报错了

**Comment by ayu250** [comment]
已经更新，再次感谢！
